DROP TABLE IF EXISTS fares;
CREATE TABLE fares(
	"ItinID" varchar
	,"MktID" varchar
	,"MktCoupons" varchar
	,"Year" int
	,"Quarter" int
	,"OriginAirportID" varchar
	,"OriginAirportSeqID" varchar
	,"OriginCityMarketID" varchar
	,"Origin" varchar
	,"OriginCountry" varchar
	,"OriginStateFips" varchar
	,"OriginState" varchar
	,"OriginStateName" varchar
	,"OriginWac" varchar
	,"DestAirportID" varchar
	,"DestAirportSeqID" varchar
	,"DestCityMarketID" varchar
	,"Dest" varchar
	,"DestCountry" varchar
	,"DestStateFips" varchar
	,"DestState" varchar
	,"DestStateName" varchar
	,"DestWac" varchar
	,"AirportGroup" varchar
	,"WacGroup" varchar
	,"TkCarrierChange" varchar
	,"TkCarrierGroup" varchar
	,"OpCarrierChange" varchar
	,"OpCarrierGroup" varchar
	,"RPCarrier" varchar
	,"TkCarrier" varchar
	,"OpCarrier" varchar
	,"BulkFare" float
	,"Passengers" varchar
	,"MktFare" float
	,"MktDistance" float
	,"MktDistanceGroup" varchar
	,"MktMilesFlown" float
	,"NonStopMiles" varchar
	,"ItinGeoType" varchar
	,"MktGeoType" varchar
	,"xx" varchar
);